version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build BikeShare
          command: npm run build -- --project=bikeshare --prod
      - run:
          name: Run Tests
          command: npm run test -- -w 1 --coverage --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js
      - run:
          name: Run TSLint
          command: npm run lint
      - run:
          name: Run Prettier
          command: npx prettier **/*.ts --check
